services:

  db:
    build:
      context: ./MessageStore
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      #- "127.0.0.1:3306:3306"
      - "3308:3306"
      #- "172.69.128.2:3307:3306"
    volumes:
      - ./MessageStore/db:/var/lib/mysql
    networks:
      sqlnet:
        ipv4_address: 172.69.128.1

  mongo:
    image: mongo:7.0.8
    restart: always
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 8081:8081
      - 27017:27017
      #- "172.69.128.2:8081:8081"
    volumes:
      - ./MessageStore/mongodb:/data/db
    networks:
      sqlnet:
        ipv4_address: 172.69.128.3
  
  message-fetch:
    depends_on:
      - db
    build:
      context: ./MessageFetch
      dockerfile: Dockerfile
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE: ${TELEGRAM_PHONE}
      TELEGRAM_PASS: ${TELEGRAM_PASS}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      IS_DOCKER: true
    volumes:
      - ./MessageFetch/app:/app
    networks:
      sqlnet:
        ipv4_address: 172.69.128.2
    healthcheck:
      test: ["CMD", "python", "/app/mysql_healthcheck.py"]
      interval: 60s
      timeout: 30s
      retries: 3

networks:
  sqlnet:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.69.0.0/16
