FROM python:3.11-slim

RUN apt update && apt install -y nano vim procps net-tools iputils-ping wget curl git

RUN pip3 install pyrogram tgcrypto pymongo deep-translator mysql-connector-python python-dotenv psycopg2-binary sqlalchemy git+https://github.com/pgvector/pgvector-python.git

RUN pip3 install sentence-transformers

ENV PYTHONPATH=/app

ADD ./Pipeline /app

WORKDIR /app

ENTRYPOINT ["python3", "-u", "/app/MessageFetch/main.py"]
